### ISSUE TITLE
Relicense

### ISSUE THREAD

**Issue by MarcusJohnson91** [shizukachan/pi-camera-raw-lj92#1]
You can't relicense permissively licensed source code as more restricted...

**Comment by shizukachan** [comment]
lj92 is BSD licensed, as per https://bitbucket.org/baldand/mlrawviewer/src/master/ and the readme.

My code is GPLv3 and the library is BSD; if you source the library from my repository, then you will have to follow the GPLv3 license. If you source the library from the other repository, then you can follow the BSD license.

Closed.

**Comment by MarcusJohnson91** [comment]
That is not how that works.

You did not create or even contribute to lj92.

It’s license is BSD-2, every line of code thats part of lj92 is BSD licensed.

I’ve notified the FSF of your license violation.

**Comment by shizukachan** [comment]
If you were more interested in promoting open source by educating me in an area I'm not familiar with, you could have tried directing me to resources to understand if there was anything wrong, and if so, what I could do to correct it. However, it seems like your goal is to threaten and harass, so I don't think there is any reason to discuss this with you anymore.

Locked - if your goal is to threaten or harass, then I have no reason to discuss anymore.

For anyone interested in this thread at all, I referenced:
https://softwareengineering.stackexchange.com/questions/180878/gplv3-project-with-bsd-library
for my earlier reply above.
